Repository paws-r/paws, pull requests merged in 2023-10, with the labels that each got.

#681 correctly handle empty profiles #680
  paws.common/DESCRIPTION
  paws.common/NEWS.md
  paws.common/R/iniutil.R
  paws.common/tests/testthat/data_ini
  paws.common/tests/testthat/test_iniutil.R
Labels: bug 🐞

#690 remove repeat processes
  paws.common/R/iniutil.R
Labels: performance 🚀

#693 Cache Unix OS environmental variables
  paws.common/DESCRIPTION
  paws.common/NAMESPACE
  paws.common/NEWS.md
  paws.common/R/cache.R
  paws.common/R/config.R
  paws.common/R/iniutil.R
  paws.common/R/onLoad.R
  paws.common/man/paws_reset_cache.Rd
  paws.common/tests/testthat/test_cache.R
  paws.common/tests/testthat/test_iniutil.R
Labels: performance 🚀

#695 Add support for web token based IAM in config files
  paws.common/DESCRIPTION
  paws.common/NEWS.md
  paws.common/R/config.R
  paws.common/R/credential_providers.R
  paws.common/tests/testthat/test_config.R
  paws.common/tests/testthat/test_config_ini
  paws.common/tests/testthat/test_config_webtoken
  paws.common/tests/testthat/test_credential_providers.R
Labels: enhancement 💡

#699 fix `NULL` method `as.POSIXct.default` for older versions of R
  paws.common/NEWS.md
  paws.common/R/xmlutil.R
Labels: bug 🐞
